"""Generated by groovy_artifacts_repository.

Hub repo for test-dep artifacts. Each logical name resolves to an
`alias` into either a per-artifact http_jar (default pinned path) or a
user-supplied label (the `*_label` overrides on the `groovy.testing`
tag). The http_jar-produced `//jar:jar` targets are already java_imports;
re-wrapping them would be both redundant and an analysis-time error
("`jars` attribute cannot contain labels of Java targets").

Body is substituted at extension time.
"""

package(default_visibility = ["//visibility:public"])

{BODY}
