# Copyright 2026-present Alberto Cavalcante. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0

# BUILD-file templates consumed by repository rules in the sibling package
# via `rctx.template(Label("//groovy/private/repositories/templates:..."))`.
# The templates are not built; they're read as data at repo-fetch time.

package(default_visibility = ["//groovy/private/repositories:__pkg__"])

exports_files([
    "sdk.BUILD.tpl",
    "local_sdk.BUILD.tpl",
])
