"""Generated by groovy_local_sdk_repository.

`sdk_path` from the user is symlinked into the repo as `{SDK_DIR}/`, so the
groovyc wrapper's `external/*/groovy-*/bin/groovyc` glob still resolves the
launcher script. {LIB_JAR} is the runtime jar path inside that symlinked tree.
"""

load("@rules_java//java:defs.bzl", "java_import")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

filegroup(
    name = "sdk",
    srcs = glob(["{SDK_DIR}/**"]),
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "groovyc",
    srcs = ["@rules_groovy//groovy/private:groovyc_wrapper.sh"],
    data = [":sdk"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "runtime_jar",
    srcs = ["{LIB_JAR}"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "groovy",
    jars = ["{LIB_JAR}"],
    visibility = ["//visibility:public"],
)
