"""Generated by groovy_sdk_repository.

Layout inside the repo:

    {SDK_DIR}/bin/groovyc          # POSIX launcher script
    {SDK_DIR}/lib/groovy-X.Y.Z.jar # runtime jar
    {SDK_DIR}/lib/*.jar            # full classpath
    {SDK_DIR}/embeddable/*.jar     # alternative groovy-all jars

The SDK is downloaded WITHOUT strip_prefix on purpose: the launcher wrapper
at //groovy/private:groovyc_wrapper.sh resolves `bin/groovyc` by globbing
`external/*/groovy-*/bin/groovyc`, which requires the SDK directory to be
present in the repo root. Chapter 6 (Groovy 4 default) cleans this up.
"""

load("@rules_java//java:defs.bzl", "java_import")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

filegroup(
    name = "sdk",
    srcs = glob(["{SDK_DIR}/**"]),
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "groovyc",
    srcs = ["@rules_groovy//groovy/private:groovyc_wrapper.sh"],
    data = [":sdk"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "runtime_jar",
    srcs = ["{LIB_JAR}"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "groovy",
    jars = ["{LIB_JAR}"],
    visibility = ["//visibility:public"],
)
