# Copyright 2025-present Alberto Cavalcante. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0

# Package for repository-rule implementations used by the module extension.
# No build targets here; the .bzl files are loaded directly from
# //groovy:extensions.bzl. The package exists so Bazel treats this directory
# as a load-time package.

package(default_visibility = ["//visibility:private"])
